services:
  _defaults:
    autowire: true
    autoconfigure: true

  Tourze\CATrustBundle\Command\:
    resource: '../../Command/'

  Tourze\CATrustBundle\Verification\Checker\CrtShChecker: ~
  Tourze\CATrustBundle\Verification\Checker\MozillaChecker: ~

  Tourze\CATrustBundle\Command\CertificateTableFormatter:
    arguments:
      $checkers:
        - '@Tourze\CATrustBundle\Verification\Checker\CrtShChecker'
        - '@Tourze\CATrustBundle\Verification\Checker\MozillaChecker'

  Tourze\CATrustBundle\Command\CertificateVerifier:
    arguments:
      $checkers:
        - '@Tourze\CATrustBundle\Verification\Checker\CrtShChecker'
        - '@Tourze\CATrustBundle\Verification\Checker\MozillaChecker'